spring:
  config:
    activate:
      on-profile: prod
  redis:
    host:
    port: 6379
    password:
    db: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://?verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username :
    password :

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    properties:
      format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB