spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
    password: player-redis
    db: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/player?verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username : hongyeongjune
    password : 1q2w3e4r!

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    properties:
      format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB