spring:
  config:
    activate:
      on-profile: test
  redis:
    host: localhost
    port: 6379
    password: medna-redis
    db: 0

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true


logging:
  level:
    org.hibernate.SQL: debug